### ISSUE TITLE
No se generan raids

### ISSUE THREAD

**Issue by CalvPonk24** [Yasser444o/Skybedrock#13]
Hello, sorry my skyblock world doesn't let me generate raids, when I take an ominous in a village nothing happens, and when I take an ominous in a test chamber if it works, you will know why it is or if my world is corrupted , I wouldn't want to lose the world because I already have a lot of progress.

**Comment by Yasser4440** [comment]
your world isn't corrupted and i am currently investigating this issue, it should be fixed by the next update.

**Comment by Yasser444o** [comment]
your world isn't corrupted and i am currently investigating this issue, it should be fixed by the next update.

**Comment by Yasser444o** [comment]
Fixed
