### ISSUE TITLE
Nether biome issue

### ISSUE THREAD

**Issue by Herobrineeee802** [Yasser444o/Skybedrock#17]
When i make the portal and go through .... the biome detector says the biome is ocean and behaves the same way...... is also makes zombies creepers and spiders spawn there.... yet no piglins or zombified piglins spawn....so i was able to conclude that the biome is glitched rather than the detector

**Comment by Yasser444o** [comment]
Thank you so much for the report, i will investigate this issue and see what i can do.

**Comment by Yasser444o** [comment]
In which coordinates did you encounter this issue?
And in which version of skybedrock? i tested the latest version and it seems fine.

**Comment by Herobrineeee802** [comment]
> In which coordinates did you encounter this issue? And in which version of skybedrock? i tested the latest version and it seems fine.

Right around 0,0,0 ... where the portal is

**Comment by Herobrineeee802** [comment]
> In which coordinates did you encounter this issue? And in which version of skybedrock? i tested the latest version and it seems fine.

The latest version 1-12-4-1

**Comment by Herobrineeee802** [comment]
![Screenshot_20241118-164153_Minecraft](https://github.com/user-attachments/assets/7953972b-7422-477d-85ab-c5cdfc966ab5)
Look ^

**Comment by Yasser444o** [comment]
hmmm, what's your game version? 
this issue isn't related to the biome detector, but rather the biome itself is broken, there has been some recent changes regarding biomes in 1.21.50 previews and betas. so they might have broken the nether.

**Comment by Herobrineeee802** [comment]
> In which coordinates did you encounter this issue? And in which version of skybedrock? i tested the latest version and it seems fine.

It was right at 0 0 0

**Comment by Herobrineeee802** [comment]
![Screenshot_20241118-164153_Minecraft](https://github.com/user-attachments/assets/0c4cdcc7-3924-4e8c-8d1b-9014adde3dfe)
Look

**Comment by Herobrineeee802** [comment]
> hmmm, what's your game version? this issue isn't related to the biome detector, but rather the biome itself is broken, there has been some recent changes regarding biomes in 1.21.50 previews and betas. so they might have broken the nether.

I play 1.21.40 mc pocket edition

**Comment by Yasser444o** [comment]
![Screenshot_20241124.jpg](https://github.com/user-attachments/assets/0fa2c346-8c3c-4c8e-90e8-1eafde8620ee)

 This is me loading the lastest skybedrock version 1.21.4.1 in Minecraft pocket edition version 1.21.41 and i can't reproduce this issue, i will mark it as resolved until you are able to make me reproduce it.
