### ISSUE TITLE
Floating sand islands fall into the void

### ISSUE THREAD

**Issue by REmerald** [Yasser444o/Skybedrock#9]
So, I was playing on a skyblock and at some point I noticed that the sand island in the distance was gone. Maybe an enderman spawned and updated the blocks.

Is there a way you could fix the floating sand islands by adding a sandstone, barriers or something else under the sand, so they don't fall into the void if a player or enderman updates them?

**Comment by Yasser444o** [comment]
Thanks for the report, i have done some testing and it appears that the only scenarios where the desert island could fall on its own is if an enderman spawned and picked up the cactus or if it got stuck by lightning. However; this behavior is intended and i don't have to change anything, try not to approach the desert island at night or in a thunderstorm next time, you got really unlucky there but don't worry, Husks drop sand, Wandering traders sell cactus, and Dead bushes can be obtained by brushing suspicious gravel.

**Comment by REmerald** [comment]
@Yasser444o, there was a thunderstorm, so I think it fell because of the lightning. I set the simulation distance to 8 chunks. Was it a bad idea that caused the lightning and mobs spawn on nearby islands? Do you recommend people leave it at 4 chunks?

Also, (I've tested in the creative that) if I place a block on top or on the side of a sand island or break anything directly near the sand (the lowest block of cactus), the island falls into the void.
Is this intended? Like the aim is that a player should build a platform below the island to not lose it?

**Comment by Yasser444o** [comment]
To be honest i haven't considered the possibility of lightning to strike the desert island before i did the testing yesterday, it's propably wise to lower your simulation distance but not really necessary (it's really really low chance) you don't have to worry about enderman if you are farther than 44 blocks from the island or if it is day time. 

For the second question, yeah, that's the intended goal, you have to build a platform below the sand island to catch all the sand and cactus.
